//
// Created by rafael-cayax on 30/9/25.
//

#ifndef BIBLIOTECAMAGICAEDDPRO1_ENUMBUSQUEDA_H
#define BIBLIOTECAMAGICAEDDPRO1_ENUMBUSQUEDA_H

enum class EnumBusqueda {
    BUSQUEDA_ISBN,
    BUSQUEDA_TITULO,
    BUSQUEDA_GENERO,
    BUSQUEDA_AÑO
};

#endif //BIBLIOTECAMAGICAEDDPRO1_ENUMBUSQUEDA_H